# Project: animation
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"E:/Setup/Dev++/MinGW64/lib" -L"E:/Setup/Dev++/MinGW64/x86_64-w64-mingw32/lib" -static -lopengl32 -lfreeglut -lglu32
INCS     = -I"E:/Setup/Dev++/MinGW64/include" -I"E:/Setup/Dev++/MinGW64/x86_64-w64-mingw32/include" -I"E:/Setup/Dev++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Setup/Dev++/MinGW64/include" -I"E:/Setup/Dev++/MinGW64/x86_64-w64-mingw32/include" -I"E:/Setup/Dev++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Setup/Dev++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = animation.exe
CXXFLAGS = $(CXXINCS) -fopenmp
CFLAGS   = $(INCS) -fopenmp
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
